// Code generated by Slice Machine. DO NOT EDIT.

import CustomerLogos from './CustomerLogos/index.svelte';
import Hero from './Hero/index.svelte';
import Image from './Image/index.svelte';
import ImageCards from './ImageCards/index.svelte';
import Quote from './Quote/index.svelte';
import SideVisualSteps from './SideVisualSteps/index.svelte';
import Text from './Text/index.svelte';
import TextWithImage from './TextWithImage/index.svelte';

export const components = {
	customer_logos: CustomerLogos,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	side_visual_steps: SideVisualSteps,
	text: Text,
	text_with_image: TextWithImage
};
